using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Xml;
using WIDA.Storage;
using WIDA.Utes;
using System.Windows.Forms;
using System.Threading;

namespace WIDA.Tasks.Actions
{
    public class Action : Definition
    {
        public delegate void Del(object[] Args);
        private Del Work = null;

        public Action(string Name, string GroupName, string Description, Source Source, bool NeedsParams, Source FormSource, object[] Args = null)
        : base(Name, GroupName, Description, Source, NeedsParams, FormSource, Args)
        {

        }

        public Action(XmlElement Element)
        : base(Element)
        {

        }

        public Action Clone()
        {
            return new Action(this.ToXML());
        }

        public override void AssignTask(Task Task)
        {
            this.Work = (Del)Compiler.SourceToDelegate(this.Source.CodeList().ToArray(), this.Source.ReferencedAssemblies.ToArray(), typeof(Del), "Code", "Action", "Work");
            base.AssignTask(Task);
        }

        public void DoAction()
        {
            //Ignore any error generated by executing the code
            try
            {
                //Run action in separate thread to prevent blocking code execution
                Thread Thread = new System.Threading.Thread(() => Work(this.Args));
                Thread.Start();
            }
            catch
            {

            }
        }

        public override void Dispose()
        {
            this.Work = null;
            base.Dispose();
        }
    }
}