using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Xml;
using WIDA.Storage;
using WIDA.Utes;
using System.Windows.Forms;

namespace WIDA.Tasks.Triggers
{
    public class Trigger : Definition
    {
        //This object stores the instance of the defined trigger class
        private object TriggerInstance = null;
        public delegate void Del();

        public Trigger(string Name, string GroupName, string Description, Source Source, bool NeedsParams, Source FormSource, object[] Args = null) 
        : base(Name, GroupName, Description, Source, NeedsParams, FormSource, Args)
        {

        }

        public Trigger(XmlElement Element)
        : base(Element)
        {

        }

        public Trigger Clone()
        {
            return new Trigger(this.ToXML());
        }

        public override void AssignTask(Task Task)
        {
            //Pass task trigger delegate to the trigger itself
            Delegate Delegate = Delegate.CreateDelegate(typeof(Del), Task, Task.GetType().GetMethod("Trigger"));   
            object[] Constructors = new object[2];
            Constructors[0] = Delegate;
            Constructors[1] = this.Args;
            this.TriggerInstance = Compiler.SourceToInstance(this.Source.CodeList().ToArray(), this.Source.ReferencedAssemblies.ToArray(), Conf.TriggerCriticals.Namespace, Conf.TriggerCriticals.Class, Constructors);
            base.AssignTask(Task);
        }

        public override void Dispose()
        {
            //Handle any error generated by executing the code
            try
            {
                this.TriggerInstance.GetType().GetMethod("Dispose").Invoke(this.TriggerInstance, null);
            }
            catch
            { }
            this.TriggerInstance = null;
            base.Dispose();
        }
    }
}
